# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 透明代理端口 (重定向 TCP 和 TProxy UDP 流量)
redir-port: 7892

# Linux 的透明代理端口（适用于 TProxy TCP 和 TProxy UDP 流量)
# tproxy-port: 7893

# 允许局域网的连接（可用来共享代理）
allow-lan: true
bind-address: "*"

# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）
mode: rule

# Clash 默认将日志输出至 STDOUT
# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出)。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# Clash 的 RESTful API 监听地址
external-controller: 127.0.0.1:9090

# RESTful API 的口令 (可选)
secret: "000000"

# 出站网卡接口
# interface-name: en0

# DNS 服务器配置
dns:
  enable: false
  listen: 0.0.0.0:53
  ipv6: false

  default-nameserver:
    - 61.139.2.69
    - 218.6.200.139
    - 8.8.8.8
  
  nameserver:
    - 61.139.2.69
    - 218.6.200.139
    
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*.lan"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - swscan.apple.com
    - mesu.apple.com
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - "+.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - "+.y.qq.com"
    - "+.music.tc.qq.com"
    - aqqmusic.tc.qq.com
    - "+.stream.qqmusic.qq.com"
    - "*.xiami.com"
    - "+.music.migu.cn"
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.microsoft.com
    - "+.xboxlive.com"
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.battlenet.com.cn"
    - "*.ffxiv.com"
    - "*.finalfantasyxiv.com"
    - "*.square-enix.com"
    - "+.nflxvideo.net"
    - stun.l.google.com
    - lens.l.google.com
    - swdist.apple.com
    - swcdn.apple.com
    - swdownload.apple.com
    - swquery.apple.com
    - "*.router.asus.com"
    - heartbeat.belkin.com
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*"
    - "+.wargaming.net"
    - "+.wowsgame.cn"
    - "+.wggames.cn"
    - "+.wotgame.cn"
    - xnotify.xboxlive.com
    - localhost.sec.qq.com
    - msftncsi.com
    - msftconnecttest.com
    - music.migu.cn
    - "*.music.migu.cn"
    - amobile.music.tc.qq.com
    - dl.stream.qqmusic.qq.com
    - isure.stream.qqmusic.qq.com
    - mobileoc.music.tc.qq.com
    - streamoc.music.tc.qq.com
    - "*.y.qq.com"
    - y.qq.com
    - "*.music.163.com"
    - music.163.com
    - "*.home.arpa"
    - "*.local"
    - "*.test"
    - "*.localhost"
    - "*.invalid"
    - "*.example"
    - "*.localdomain"
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - "*.taobao.com"
    - "*.snssdk.com"
    - "*.toutiaostatic.com"
    - "*.zijieapi.com"
    - "*.ibytedapm.com"
    - "*.toutiaoimg.com"
    - "*.bdxiguastatic.com"
    - "*.ttwebview.com"
    # 更多域名过滤规则...

  # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
  # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
  # fallback-filter:
  #   geoip: false
  #   ipcidr:
  #     - 240.0.0.0/4
  #     - 0.0.0.0/32
  #   domain:
  #     - '+.google.com'
  #     - '+.facebook.com'
  #     - '+.youtube.com'

# TUN 配置
tun:
  enable: false #如果需要启用 TUN 模式，请设置为 true
  stack: system # 或 gvisor
  auto-route: true
  auto-detect-interface: true
  #dns-hijack:
    #- tcp://8.8.8.8:53
    #- tcp://1.1.1.1:53
